spring.kakfa.consumer.bootstrap-servers: localhost:9092
spring.kakfa.consumer.group-id: myGroup
spring.kafka.consumer.auto-offset-reset: earliest
spring.kafka.consumer.key-deserealizer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserealizer: org.apache.kafka.common.serialization.StringDeserializer
